#!/usr/bin/env python3
"""Rig the static CopMan GLB with the Franklin humanoid armature.

Run with Blender, not the system Python:

    /Applications/Blender.app/Contents/MacOS/Blender \
      --background --factory-startup --python rig_copman.py -- \
      --cop-glb /path/to/police+officer+3d+model.glb

The donor and output paths default to their locations in the Franklin Game
workspace. Source assets are read-only; generated artifacts are written only to
ArtSource/CopManRig/dist unless explicitly overridden.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import sys
from collections import Counter
from pathlib import Path
from typing import Any, Iterable

import bpy
from mathutils import Matrix, Vector


SCRIPT_PATH = Path(__file__).resolve()
RIG_ROOT = SCRIPT_PATH.parent
REPOSITORY_ROOT = RIG_ROOT.parents[1]
DEFAULT_COP_GLB = Path.home() / "Downloads" / "police+officer+3d+model.glb"
DEFAULT_DONOR_FBX = (
    REPOSITORY_ROOT / "Assets" / "Character" / "Franklin" / "franklin_1_fixed.fbx"
)
DEFAULT_OUTPUT_DIR = RIG_ROOT / "dist"

EXPECTED_COP_VERTICES = 8_649
EXPECTED_COP_TRIANGLES = 5_861
EXPECTED_DONOR_BONES = 68
MAX_INFLUENCES = 4
WEIGHT_EPSILON = 1.0e-6
WEIGHT_SUM_TOLERANCE = 1.0e-5


def parse_args() -> argparse.Namespace:
    blender_args = sys.argv[sys.argv.index("--") + 1 :] if "--" in sys.argv else []
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--cop-glb",
        type=Path,
        default=DEFAULT_COP_GLB,
        help=f"Static CopMan GLB (default: {DEFAULT_COP_GLB})",
    )
    parser.add_argument(
        "--donor-fbx",
        type=Path,
        default=DEFAULT_DONOR_FBX,
        help=f"Rigged Franklin donor FBX (default: {DEFAULT_DONOR_FBX})",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help=f"Generated artifact directory (default: {DEFAULT_OUTPUT_DIR})",
    )
    parser.add_argument(
        "--output-stem",
        default="CopMan_Rigged",
        help="Base filename for generated FBX, Blend, and QA JSON files",
    )
    parser.add_argument(
        "--no-blend",
        action="store_true",
        help="Skip the optional reusable .blend output",
    )
    return parser.parse_args(blender_args)


def require_file(path: Path, label: str) -> Path:
    path = path.expanduser().resolve()
    if not path.is_file():
        raise FileNotFoundError(f"{label} does not exist: {path}")
    return path


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def clear_scene() -> None:
    bpy.ops.wm.read_factory_settings(use_empty=True)


def import_fbx(path: Path) -> list[bpy.types.Object]:
    before = set(bpy.data.objects)
    result = bpy.ops.import_scene.fbx(filepath=str(path), use_anim=False)
    if "FINISHED" not in result:
        raise RuntimeError(f"Blender failed to import donor FBX: {path}")
    return [obj for obj in bpy.data.objects if obj not in before]


def import_glb(path: Path) -> list[bpy.types.Object]:
    before = set(bpy.data.objects)
    result = bpy.ops.import_scene.gltf(filepath=str(path), import_shading="NORMALS")
    if "FINISHED" not in result:
        raise RuntimeError(f"Blender failed to import CopMan GLB: {path}")
    return [obj for obj in bpy.data.objects if obj not in before]


def exactly_one(objects: Iterable[bpy.types.Object], kind: str, label: str) -> bpy.types.Object:
    matches = [obj for obj in objects if obj.type == kind]
    if len(matches) != 1:
        names = [f"{obj.name}:{obj.type}" for obj in objects]
        raise RuntimeError(
            f"Expected exactly one {kind} in {label}, found {len(matches)}. Objects: {names}"
        )
    return matches[0]


def triangle_count(mesh: bpy.types.Mesh) -> int:
    return sum(max(0, len(polygon.vertices) - 2) for polygon in mesh.polygons)


def world_dimensions(obj: bpy.types.Object) -> tuple[float, float, float]:
    corners = [obj.matrix_world @ Vector(corner) for corner in obj.bound_box]
    return tuple(
        max(corner[axis] for corner in corners) - min(corner[axis] for corner in corners)
        for axis in range(3)
    )


def rounded_vector(values: Iterable[float]) -> list[float]:
    return [round(float(value), 8) for value in values]


def flip_uv_vertical_for_unity_texture(mesh_obj: bpy.types.Object) -> int:
    """Match the PNG generated by Piglet from the source glTF texture.

    Piglet stores the imported image vertically flipped for Unity's texture
    convention. Blender's glTF importer instead adapts the UVs while keeping the
    original image orientation. Flip V once before FBX export so the rigged mesh
    can reuse CopMan's existing Unity material and PNG without an atlas mismatch.
    """
    coordinate_count = 0
    for uv_layer in mesh_obj.data.uv_layers:
        for loop_uv in uv_layer.data:
            loop_uv.uv.y = 1.0 - loop_uv.uv.y
            coordinate_count += 1
    mesh_obj.data.update()
    return coordinate_count


def select_only(*objects: bpy.types.Object) -> None:
    bpy.ops.object.select_all(action="DESELECT")
    for obj in objects:
        obj.hide_set(False)
        obj.hide_viewport = False
        obj.select_set(True)
    bpy.context.view_layer.objects.active = objects[-1]


def transfer_weights(
    donor_mesh: bpy.types.Object,
    cop_mesh: bpy.types.Object,
) -> None:
    for group in list(cop_mesh.vertex_groups):
        cop_mesh.vertex_groups.remove(group)
    for donor_group in donor_mesh.vertex_groups:
        cop_mesh.vertex_groups.new(name=donor_group.name)

    modifier = cop_mesh.modifiers.new(name="FranklinNearestFaceWeights", type="DATA_TRANSFER")
    modifier.object = donor_mesh
    modifier.use_vert_data = True
    modifier.data_types_verts = {"VGROUP_WEIGHTS"}
    modifier.vert_mapping = "POLYINTERP_NEAREST"
    modifier.layers_vgroup_select_src = "ALL"
    modifier.layers_vgroup_select_dst = "NAME"

    select_only(cop_mesh)
    result = bpy.ops.object.modifier_apply(modifier=modifier.name)
    if "FINISHED" not in result:
        raise RuntimeError("Could not apply nearest-face vertex-weight transfer")

    bpy.ops.object.vertex_group_normalize_all(lock_active=False)
    bpy.ops.object.vertex_group_limit_total(group_select_mode="ALL", limit=MAX_INFLUENCES)
    bpy.ops.object.vertex_group_normalize_all(lock_active=False)


def attach_to_armature(
    cop_mesh: bpy.types.Object,
    armature: bpy.types.Object,
) -> None:
    # The donor FBX uses centimeter-space mesh/bone data under an armature object
    # scaled to 0.01. Convert CopMan's meter-space GLB vertices into that same
    # armature-local space while preserving the visible world-space pose.
    mesh_to_armature = armature.matrix_world.inverted() @ cop_mesh.matrix_world
    cop_mesh.data.transform(mesh_to_armature)
    cop_mesh.data.update()

    cop_mesh.parent = armature
    cop_mesh.matrix_parent_inverse = Matrix.Identity(4)
    cop_mesh.matrix_basis = Matrix.Identity(4)

    armature_modifier = cop_mesh.modifiers.new(name=armature.name, type="ARMATURE")
    armature_modifier.object = armature
    armature_modifier.use_deform_preserve_volume = False


def weight_stats(mesh_obj: bpy.types.Object) -> dict[str, Any]:
    group_usage = Counter()
    influence_distribution = Counter()
    weight_sums: list[float] = []
    zero_weight_vertices = 0

    for vertex in mesh_obj.data.vertices:
        weights = []
        for membership in vertex.groups:
            if membership.weight <= WEIGHT_EPSILON:
                continue
            weights.append(float(membership.weight))
            group_usage[membership.group] += 1
        influence_distribution[len(weights)] += 1
        if not weights:
            zero_weight_vertices += 1
            weight_sums.append(0.0)
        else:
            weight_sums.append(sum(weights))

    group_names = [group.name for group in mesh_obj.vertex_groups]
    used_group_names = [
        group_names[index] for index in range(len(group_names)) if group_usage[index] > 0
    ]
    empty_group_names = [
        group_names[index] for index in range(len(group_names)) if group_usage[index] == 0
    ]
    populated_influence_counts = [
        count for count, vertices in influence_distribution.items() if vertices > 0
    ]
    max_sum_error = max(abs(total - 1.0) for total in weight_sums)

    return {
        "vertexCount": len(mesh_obj.data.vertices),
        "vertexGroupCount": len(group_names),
        "groupsWithWeights": len(used_group_names),
        "emptyGroups": empty_group_names,
        "zeroWeightVertices": zero_weight_vertices,
        "minInfluencesPerVertex": min(populated_influence_counts),
        "maxInfluencesPerVertex": max(populated_influence_counts),
        "averageInfluencesPerVertex": round(
            sum(count * vertices for count, vertices in influence_distribution.items())
            / len(mesh_obj.data.vertices),
            6,
        ),
        "influenceDistribution": {
            str(count): influence_distribution[count]
            for count in sorted(influence_distribution)
        },
        "minWeightSum": round(min(weight_sums), 9),
        "maxWeightSum": round(max(weight_sums), 9),
        "maxWeightSumError": round(max_sum_error, 9),
    }


def mesh_stats(mesh_obj: bpy.types.Object) -> dict[str, Any]:
    stats = weight_stats(mesh_obj)
    stats.update(
        {
            "triangleCount": triangle_count(mesh_obj.data),
            "uvLayerCount": len(mesh_obj.data.uv_layers),
            "uvLayerNames": [layer.name for layer in mesh_obj.data.uv_layers],
            "materialSlotCount": len(mesh_obj.material_slots),
            "materialNames": [
                slot.material.name if slot.material is not None else None
                for slot in mesh_obj.material_slots
            ],
            "worldDimensions": rounded_vector(world_dimensions(mesh_obj)),
            "armatureModifierCount": sum(
                modifier.type == "ARMATURE" for modifier in mesh_obj.modifiers
            ),
        }
    )
    return stats


def validate_weight_stats(stats: dict[str, Any], label: str) -> None:
    failures = []
    if stats["zeroWeightVertices"] != 0:
        failures.append(f"{stats['zeroWeightVertices']} vertices have no weights")
    if stats["maxInfluencesPerVertex"] > MAX_INFLUENCES:
        failures.append(
            f"max influences is {stats['maxInfluencesPerVertex']} (expected <= {MAX_INFLUENCES})"
        )
    if stats["maxWeightSumError"] > WEIGHT_SUM_TOLERANCE:
        failures.append(
            f"max normalized-weight error is {stats['maxWeightSumError']}"
        )
    if failures:
        raise RuntimeError(f"{label} weight validation failed: " + "; ".join(failures))


def export_fbx(
    output_path: Path,
    armature: bpy.types.Object,
    cop_mesh: bpy.types.Object,
) -> None:
    select_only(armature, cop_mesh)
    result = bpy.ops.export_scene.fbx(
        filepath=str(output_path),
        use_selection=True,
        object_types={"ARMATURE", "MESH"},
        use_mesh_modifiers=True,
        use_mesh_edges=False,
        use_tspace=True,
        add_leaf_bones=False,
        primary_bone_axis="Y",
        secondary_bone_axis="X",
        armature_nodetype="NULL",
        use_armature_deform_only=False,
        bake_anim=False,
        path_mode="COPY",
        embed_textures=True,
        axis_forward="-Z",
        axis_up="Y",
    )
    if "FINISHED" not in result:
        raise RuntimeError(f"Blender failed to export FBX: {output_path}")


def save_blend(output_path: Path) -> None:
    result = bpy.ops.wm.save_as_mainfile(filepath=str(output_path), compress=True)
    if "FINISHED" not in result:
        raise RuntimeError(f"Blender failed to save staging blend: {output_path}")


def roundtrip_validate(fbx_path: Path) -> dict[str, Any]:
    clear_scene()
    imported = import_fbx(fbx_path)
    armature = exactly_one(imported, "ARMATURE", "round-tripped FBX")
    mesh = exactly_one(imported, "MESH", "round-tripped FBX")
    stats = mesh_stats(mesh)
    stats["armatureBoneCount"] = len(armature.data.bones)
    stats["armatureObjectName"] = armature.name
    stats["meshObjectName"] = mesh.name
    validate_weight_stats(stats, "Round-tripped FBX")
    if stats["armatureBoneCount"] != EXPECTED_DONOR_BONES:
        raise RuntimeError(
            f"Round-tripped FBX has {stats['armatureBoneCount']} bones; "
            f"expected {EXPECTED_DONOR_BONES}"
        )
    return stats


def main() -> None:
    args = parse_args()
    cop_glb = require_file(args.cop_glb, "CopMan source GLB")
    donor_fbx = require_file(args.donor_fbx, "Franklin donor FBX")
    output_dir = args.output_dir.expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    output_fbx = output_dir / f"{args.output_stem}.fbx"
    output_blend = output_dir / f"{args.output_stem}.blend"
    output_report = output_dir / f"{args.output_stem}_QA.json"

    clear_scene()
    donor_objects = import_fbx(donor_fbx)
    armature = exactly_one(donor_objects, "ARMATURE", "Franklin donor FBX")
    donor_mesh = exactly_one(donor_objects, "MESH", "Franklin donor FBX")

    donor_bone_count = len(armature.data.bones)
    donor_mesh_vertex_count = len(donor_mesh.data.vertices)
    donor_group_names = [group.name for group in donor_mesh.vertex_groups]
    donor_world_dimensions = world_dimensions(donor_mesh)
    if donor_bone_count != EXPECTED_DONOR_BONES:
        raise RuntimeError(
            f"Donor contains {donor_bone_count} bones; expected {EXPECTED_DONOR_BONES}"
        )
    if len(donor_group_names) != EXPECTED_DONOR_BONES:
        raise RuntimeError(
            f"Donor contains {len(donor_group_names)} vertex groups; "
            f"expected {EXPECTED_DONOR_BONES}"
        )

    cop_objects = import_glb(cop_glb)
    cop_mesh = exactly_one(cop_objects, "MESH", "CopMan GLB")
    cop_vertex_count = len(cop_mesh.data.vertices)
    cop_triangle_count = triangle_count(cop_mesh.data)
    cop_world_dimensions_before = world_dimensions(cop_mesh)
    if cop_vertex_count != EXPECTED_COP_VERTICES:
        raise RuntimeError(
            f"CopMan contains {cop_vertex_count} vertices; expected {EXPECTED_COP_VERTICES}"
        )
    if cop_triangle_count != EXPECTED_COP_TRIANGLES:
        raise RuntimeError(
            f"CopMan contains {cop_triangle_count} triangles; expected {EXPECTED_COP_TRIANGLES}"
        )

    flipped_uv_coordinate_count = flip_uv_vertical_for_unity_texture(cop_mesh)
    if flipped_uv_coordinate_count == 0:
        raise RuntimeError("CopMan has no UV coordinates to prepare for the Unity texture")

    transfer_weights(donor_mesh, cop_mesh)
    transferred_stats = mesh_stats(cop_mesh)
    validate_weight_stats(transferred_stats, "Transferred CopMan mesh")

    attach_to_armature(cop_mesh, armature)
    cop_mesh.name = "CopMan_Mesh"
    cop_mesh.data.name = "CopMan_Mesh"
    armature.name = "root"
    armature.data.name = "root"
    armature.data.pose_position = "REST"
    for pose_bone in armature.pose.bones:
        pose_bone.matrix_basis = Matrix.Identity(4)

    bpy.data.objects.remove(donor_mesh, do_unlink=True)
    for obj in list(bpy.context.scene.objects):
        if obj not in {armature, cop_mesh}:
            bpy.data.objects.remove(obj, do_unlink=True)
    bpy.ops.outliner.orphans_purge(do_recursive=True)

    staged_stats = mesh_stats(cop_mesh)
    validate_weight_stats(staged_stats, "Staged CopMan mesh")
    world_size_delta = [
        abs(after - before)
        for before, after in zip(cop_world_dimensions_before, world_dimensions(cop_mesh))
    ]
    if max(world_size_delta) > 1.0e-5:
        raise RuntimeError(
            "Attaching CopMan to the donor armature changed its visible dimensions: "
            f"delta={world_size_delta}"
        )

    if not args.no_blend:
        save_blend(output_blend)
    export_fbx(output_fbx, armature, cop_mesh)
    roundtrip_stats = roundtrip_validate(output_fbx)

    checks = {
        "sourceVertexCountMatches": cop_vertex_count == EXPECTED_COP_VERTICES,
        "sourceTriangleCountMatches": cop_triangle_count == EXPECTED_COP_TRIANGLES,
        "donorBoneCountMatches": donor_bone_count == EXPECTED_DONOR_BONES,
        "donorGroupCountMatches": len(donor_group_names) == EXPECTED_DONOR_BONES,
        "allVerticesWeighted": staged_stats["zeroWeightVertices"] == 0,
        "maximumFourInfluences": staged_stats["maxInfluencesPerVertex"] <= MAX_INFLUENCES,
        "weightsNormalized": staged_stats["maxWeightSumError"] <= WEIGHT_SUM_TOLERANCE,
        "uvPreparedForUnityTexture": staged_stats["uvLayerCount"] > 0
        and flipped_uv_coordinate_count > 0,
        "materialSlotPreserved": staged_stats["materialSlotCount"] > 0,
        "worldDimensionsPreserved": max(world_size_delta) <= 1.0e-5,
        "fbxRoundtripBoneCountMatches": roundtrip_stats["armatureBoneCount"]
        == EXPECTED_DONOR_BONES,
        "fbxRoundtripAllVerticesWeighted": roundtrip_stats["zeroWeightVertices"] == 0,
        "fbxRoundtripMaximumFourInfluences": roundtrip_stats["maxInfluencesPerVertex"]
        <= MAX_INFLUENCES,
    }
    if not all(checks.values()):
        raise RuntimeError(f"One or more final QA checks failed: {checks}")

    report = {
        "schemaVersion": 2,
        "status": "passed",
        "blenderVersion": bpy.app.version_string,
        "method": {
            "weightTransfer": "POLYINTERP_NEAREST",
            "normalizeBeforeLimit": True,
            "maximumInfluencesPerVertex": MAX_INFLUENCES,
            "normalizeAfterLimit": True,
            "donorMeshRemoved": True,
            "exportedObjectTypes": ["ARMATURE", "MESH"],
            "stagedRotationYDegrees": 0,
            "uvAdjustment": "V = 1 - V for existing Piglet-flipped Unity PNG",
            "flippedUvCoordinateCount": flipped_uv_coordinate_count,
        },
        "sources": {
            "copGlb": {
                "path": str(cop_glb),
                "sha256": sha256(cop_glb),
                "vertexCount": cop_vertex_count,
                "triangleCount": cop_triangle_count,
                "worldDimensions": rounded_vector(cop_world_dimensions_before),
            },
            "donorFbx": {
                "path": str(donor_fbx),
                "sha256": sha256(donor_fbx),
                "meshVertexCount": donor_mesh_vertex_count,
                "boneCount": donor_bone_count,
                "vertexGroupCount": len(donor_group_names),
                "worldDimensions": rounded_vector(donor_world_dimensions),
            },
        },
        "stagedMesh": staged_stats,
        "fbxRoundtrip": roundtrip_stats,
        "checks": checks,
        "outputs": {
            "fbx": {
                "path": str(output_fbx),
                "bytes": output_fbx.stat().st_size,
                "sha256": sha256(output_fbx),
            },
            "blend": None
            if args.no_blend
            else {
                "path": str(output_blend),
                "bytes": output_blend.stat().st_size,
                "sha256": sha256(output_blend),
            },
            "qaReport": str(output_report),
        },
    }
    output_report.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")

    print(f"COPMAN_RIG_FBX={output_fbx}")
    if not args.no_blend:
        print(f"COPMAN_RIG_BLEND={output_blend}")
    print(f"COPMAN_RIG_QA={output_report}")
    print("COPMAN_RIG_STATUS=passed")


if __name__ == "__main__":
    try:
        main()
    except Exception as error:
        print(f"COPMAN_RIG_STATUS=failed: {error}", file=sys.stderr)
        raise
